include:
  - local: ".gitlab-ci-config.yml"
  - local: ".gitlab-ci-release.yml"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "${CI_JOB_NAME}"'
# cache:
#   paths:
#     - .m2/repository

image: $NEXUS_IMAGE_BASE/$NEXUS_IMAGE

stages:
  - build
  - release

build_snapshot:
  stage: build
  rules:
    - if: $CI_COMMIT_REF_NAME == $BRANCH_NAME
  script: |
    mvn clean deploy
    scp -s target/config-server-*.jar "${SFTP_TARGET}:${SFTP_FOLDER}/config-server.jar"
