################################################################################
# These variables are shared by the build files, and should be the only place
# where customization is required in other branches (i.e. prc, bcgeu, etc.)
#  
# The intent here is to ensure that the build and release scripts for each branch
# remain identical, and only this file changes branch-to-branch
################################################################################

variables:
  ARM_CLIENT:   &client "arkcase"
  BRANCH_NAME:  "develop"
  GIT_URL:      "git@${CI_SERVER_HOST}:${CI_PROJECT_PATH}.git"
  # SFTP_USER:    *client
  # SFTP_FOLDER:  "/from-arkcase"
  SFTP_TARGET:  "${SFTP_USER}@${SFTP_SERVER}"

  # We shouldn't disable SSL verification here
  # GIT_SSL_NO_VERIFY: "true"
  # GIT_STRATEGY: "clone"

  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  # MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
