version: "3.7"

services:
  activemq:
    image: rmohr/activemq:5.15.9-alpine
    init: true

  acm-config-server:
    image: arkcase/acm-config-server
    build:
      context: .
    init: true
    ports:
      - 9999:9999
    environment:
      ACTIVEMQ_URL: tcp://activemq:61616
    volumes:
      - ./.arkcase/acm/acm-config-server-repo:/app/data
    depends_on:
      - activemq
