server.port: 9999
spring:
  profiles.active: native
  cloud:
    config.server:
      native.searchLocations: file:${user.home}/.arkcase/acm/acm-config-server-repo,file:${user.home}/.arkcase/acm/acm-config-server-repo/labels,file:${user.home}/.arkcase/acm/acm-config-server-repo/ldap,file:${user.home}/.arkcase/acm/acm-config-server-repo/lookups,file:${user.home}/.arkcase/acm/acm-config-server-repo/rules,file:${user.home}/.arkcase/acm/acm-config-server-repo/schemas/form,file:${user.home}/.arkcase/acm/acm-config-server-repo/schemas/menu,file:${user.home}/.arkcase/acm/acm-config-server-repo/schemas/query
  jms:
    pub-sub-domain: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#spring.cloud.config.server.git.uri: file:///c:/dev/arkcase-config
#spring.cloud.config.server.git.clone-on-start: true
#spring.security.user.name: root
#spring.security.user.password: root
#management.endpoints.web.exposure.include: *
properties.folder.path: ${user.home}/.arkcase/acm/acm-config-server-repo
branding.files.folder.path: ${user.home}/.arkcase/acm/acm-config-server-repo/branding
avro.schema.files.folder.path: ${user.home}/.arkcase/acm/acm-config-server-repo/schemas/avro
schema.files.folder.path: ${user.home}/.arkcase/acm/acm-config-server-repo/schemas
process.files.folder.path: ${user.home}/.arkcase/acm/acm-config-server-repo/processes
logging:
  file.max-history: 10
  file.max-size: 10MB
  file.name: logs/acmConfigServer.log
  level:
    com.armedia.acm.configserver: debug
    org.springframework.cloud.config: debug
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss,SSS} [%thread] %-5level %logger.%M - %msg%n"
jms.message.buffer.window: 1
acm.activemq:
  broker-url: ssl://acm-arkcase:61616
  keystore: ${user.home}/.arkcase/acm/private/arkcase.ks
  keystore-password: AcMd3v$
  truststore: ${user.home}/.arkcase/acm/private/arkcase.ts
  truststore-password: password
  user: "guest"
  password: "guest"
  timeout: 10 #seconds
  messageBufferWindow: 1
  default-destination: configuration.changed
  destinations:
    labels-destination: labels.changed
    ldap-destination: ldap.changed
    lookups-destination: lookups.changed
    rules-destination: rules.changed
    permissions-destination: permissions.changed
arkcase:
  languages: "-de,-en,-en-in,-es,-fr,-hi,-ja,-pt,-ru,-zh-cn,-zh-tw"
management:
  endpoints:
    web:
      exposure:
        include: '*'
