server.port: 9999
spring:
  profiles.active: native
  cloud:
    config.server:
      native.searchLocations: file:${user.home}/.arkcase/acm/acm-config-server-repo,file:${user.home}/.arkcase/acm/acm-config-server-repo/labels,file:${user.home}/.arkcase/acm/acm-config-server-repo/ldap,file:${user.home}/.arkcase/acm/acm-config-server-repo/lookups,file:${user.home}/.arkcase/acm/acm-config-server-repo/rules
    bus:
      enabled: true
  kafka:
    bootstrap-servers: acm-arkcase:9092
    producer:
      retries: 1
      bootstrap-servers:
      - acm-arkcase:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#spring.cloud.config.server.git.uri: file:///c:/dev/arkcase-config
#spring.cloud.config.server.git.clone-on-start: true
#spring.security.user.name: root
#spring.security.user.password: root
#management.endpoints.web.exposure.include: *
properties.folder.path: ${user.home}/.arkcase/acm/acm-config-server-repo
branding.files.folder.path: ${user.home}/.arkcase/acm/acm-config-server-repo/branding
schema.files.folder.path: ${user.home}/.arkcase/acm/acm-config-server-repo/schemas
process.files.folder.path: ${user.home}/.arkcase/acm/acm-config-server-repo/processes
logging:
  file.max-history: 10
  file.max-size: 10MB
  file.name: logs/acmConfigServer.log
  level:
    com.armedia.acm.configserver: debug
    org.springframework.cloud.config: debug
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss,SSS} [%thread] %-5level %logger.%M - %msg%n"
arkcase.languages: "-de,-en,-en-in,-es,-fr,-hi,-ja,-pt,-ru,-zh-cn,-zh-tw"

management:
  endpoints:
    web:
      exposure:
        include: '*'
