server.port: 9999
spring:
  profiles.active: native
  profiles:
    include: awss3, jdbc, native
  jms:
    pub-sub-domain: true
  datasource:
    # Database connection should be added here
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/config
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    config:
      server:
        jdbc:
          order: 0
          sql: "SELECT key, value from properties where application = ? and profile = ? and label = ?"
        native:
          searchLocations: file:${user.home}/.arkcase/acm/acm-config-server-repo,file:${user.home}/.arkcase/acm/acm-config-server-repo/labels,file:${user.home}/.arkcase/acm/acm-config-server-repo/ldap,file:${user.home}/.arkcase/acm/acm-config-server-repo/lookups,file:${user.home}/.arkcase/acm/acm-config-server-repo/rules
          order: 1
        awss3:
          endpoint: http://127.0.0.1:9000
          order: 2
          bucket: arkcase
          region: us-east-1
        bootstrap: true
        fail-on-composite-error: false
        default-application-name:
    aws:
      s3:
        endpoint: http://127.0.0.1:9000  # MinIO endpoint
        bucket: arkcase
      region:
        static: us-east-1  # Required region
      credentials:
        access-key: minioadmin
        secret-key: minioadmin

sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql


#spring.cloud.config.server.git.uri: file:///c:/dev/arkcase-config
#spring.cloud.config.server.git.clone-on-start: true
#spring.security.user.name: root
#spring.security.user.password: root
#management.endpoints.web.exposure.include: *
properties.folder.path: ${user.home}/.arkcase/acm/acm-config-server-repo
branding.files.folder.path: ${user.home}/.arkcase/acm/acm-config-server-repo/branding
logging:
  level:
    org.hibernate: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.type: ERROR
    org.hibernate.type.descriptor: ERROR
    org.hibernate.type.descriptor.sql: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    com.armedia.acm.configserver: debug
    org.springframework.cloud.config: debug
    org.springframework.cloud.aws: DEBUG

  file.max-history: 10
  file.max-size: 10MB
  file: logs/acmConfigServer.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss,SSS} [%thread] %-5level %logger.%M - %msg%n"
jms.message.buffer.window: 1
acm.activemq:
  broker-url: ssl://acm-arkcase:61616
  keystore: ${user.home}/.arkcase/acm/private/arkcase.ks
  keystore-password: AcMd3v$
  truststore: ${user.home}/.arkcase/acm/private/arkcase.ts
  truststore-password: password
  user: "guest"
  password: "guest"
  default-destination: configuration.changed
  labels-destination: labels.changed
  ldap-destination: ldap.changed
  lookups-destination: lookups.changed
  rules-destination: rules.changed
  permissions-destination: permissions.changed
  timeout: 10 #seconds
arkcase:
  languages:
    - "-de"
    - "-en"
    - "-en-in"
    - "-es"
    - "-fr"
    - "-hi"
    - "-ja"
    - "-pt"
    - "-ru"
    - "-zh-cn"
    - "-zh-tw"
    - "-ar"
  folders: # list of folders monitored for runtime changes
    - "${user.home}/.arkcase/acm/acm-config-server-repo"
    - "${user.home}/.arkcase/acm/acm-config-server-repo/labels"
    - "${user.home}/.arkcase/acm/acm-config-server-repo/ldap"
    - "${user.home}/.arkcase/acm/acm-config-server-repo/lookups"
