server.port: 9999
spring:
  profiles.active: native
  cloud:
    config.server:
      native.searchLocations: file:${user.home}/.arkcase/acm/acm-config-server-repo,file:${user.home}/.arkcase/acm/acm-config-server-repo/labels,file:${user.home}/.arkcase/acm/acm-config-server-repo/ldap,file:${user.home}/.arkcase/acm/acm-config-server-repo/lookups,file:${user.home}/.arkcase/acm/acm-config-server-repo/rules,file:${user.home}/.arkcase/acm/acm-config-server-repo/forms
    bus:
      enabled: true
  kafka:
    bootstrap-servers: acm-arkcase:9092
#spring.cloud.config.server.git.uri: file:///c:/dev/arkcase-config
#spring.cloud.config.server.git.clone-on-start: true
#spring.security.user.name: root
#spring.security.user.password: root
#management.endpoints.web.exposure.include: *
properties.folder.path: ${user.home}/.arkcase/acm/acm-config-server-repo
branding.files.folder.path: ${user.home}/.arkcase/acm/acm-config-server-repo/branding
schema.files.folder.path: ${user.home}/.arkcase/acm/acm-config-server-repo/schemas
process.files.folder.path: ${user.home}/.arkcase/acm/acm-config-server-repo/processes
logging:
  file.max-history: 10
  file.max-size: 10MB
  file.name: logs/acmConfigServer.log
  level:
    com.armedia.acm.configserver: debug
    org.springframework.cloud.config: debug
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss,SSS} [%thread] %-5level %logger.%M - %msg%n"
arkcase.languages: "-de,-en,-en-in,-es,-fr,-hi,-ja,-pt,-ru,-zh-cn,-zh-tw"
arkcase:
  kafka:
    messageBufferWindow: 1
    bootstrapAddress: acm-arkcase:9092
    configuration-changed-topic: ark-config-event-configuration
    configuration-changed-topic-replicas: 1
    configuration-changed-topic-partitions: 1
    labels-changed-topic: ark-config-event-labels
    labels-changed-topic-replicas: 1
    labels-changed-topic-partitions: 1
    ldap-changed-topic: ark-config-event-ldap
    ldap-changed-topic-replicas: 1
    ldap-changed-topic-partitions: 1
    lookups-changed-topic: ark-config-event-lookups
    lookups-changed-topic-replicas: 1
    lookups-changed-topic-partitions: 1
    rules-changed-topic: ark-config-event-rules
    rules-changed-topic-replicas: 1
    rules-changed-topic-partitions: 1
    forms-changed-topic: ark-config-event-forms
    forms-changed-topic-replicas: 1
    forms-changed-topic-partitions: 1
    configuration-file-created-topic: ark-config-event-configuration-file
    configuration-file-created-topic-replicas: 1
    configuration-file-created-topic-partitions: 1
    form-schema-file-topic: ark-event-form-schema
    form-schema-file-topic-replicas: 1
    form-schema-file-topic-partitions: 1
    menu-schema-file-topic: ark-event-menu-schema
    menu-schema-file-topic-replicas: 1
    menu-schema-file-topic-partitions: 1
    avro-schema-file-topic: ark-event-avro-schema
    avro-schema-file-topic-replicas: 1
    avro-schema-file-topic-partitions: 1
    process-file-topic: ark-event-process
    process-file-topic-replicas: 1
    process-file-topic-partitions: 1
    retention-ms: "86400000"
management:
  endpoints:
    web:
      exposure:
        include: '*'
