server.port: 9999
spring:
  profiles.active: native
  cloud.config.server:
    native.searchLocations: file:${user.home}/.arkcase/acm/acm-config-server-repo,file:${user.home}/.arkcase/acm/acm-config-server-repo/labels
  jms:
    pub-sub-domain: true
#spring.cloud.config.server.git.uri: file:///c:/dev/arkcase-config
#spring.cloud.config.server.git.clone-on-start: true
#spring.security.user.name: root
#spring.security.user.password: root
#management.endpoints.web.exposure.include: *
properties.folder.path: ${user.home}/.arkcase/acm/acm-config-server-repo
logging:
  file.max-history: 10
  file.max-size: 10MB
  file: logs/acmConfigServer.log
  level:
    com.armedia.acm.configserver: debug
    org.springframework.cloud.config: debug
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss,SSS} [%thread] %-5level %logger.%M - %msg%n"
jms.message.buffer.window: 1
acm.activemq:
  broker-url: ssl://acm-activemq:61616
  keystore: ${user.home}/.arkcase/acm/private/keystore.old
  keystore-password: password
  truststore: ${user.home}/.arkcase/acm/private/truststore
  truststore-password: AcMd3v$
  default-destination: configuration.changed
  labels-destination: labels.changed
  timeout: 10 #seconds