server.port: 8888
spring:
  profiles.active: native
  cloud.config.server.native:
    searchLocations: acm-config-server-repo
    addLabelLocations: false
  activemq:
    broker-url: ssl://acm-activemq:61616
    user: guest
    password: guest
  jms:
    pub-sub-domain: true
#spring.cloud.config.server.git.uri: file:///c:/dev/arkcase-config
#spring.cloud.config.server.git.clone-on-start: true
#spring.security.user.name: root
#spring.security.user.password: root
#management.endpoints.web.exposure.include: *
propertiesPath: acm-config-server-repo/arkcase-runtime.yaml
propertiesFolderPath: acm-config-server-repo
logging:
  file.max-history: 10
  file.max-size: 10MB
  file: logs/configServer.log
  level:
    com.armedia.acm.configserver: debug
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss,SSS} [%thread] %-5level %logger.%M - %msg%n"
