server.port: 9999
spring:
  profiles.active: native
  cloud.config.server:
    native.searchLocations: file:${user.home}/.arkcase/acm/acm-config-server-repo,file:${user.home}/.arkcase/acm/acm-config-server-repo/labels,file:${user.home}/.arkcase/acm/acm-config-server-repo/ldap,file:${user.home}/.arkcase/acm/acm-config-server-repo/lookups,file:${user.home}/.arkcase/acm/acm-config-server-repo/rules
  jms:
    pub-sub-domain: true
#spring.cloud.config.server.git.uri: file:///c:/dev/arkcase-config
#spring.cloud.config.server.git.clone-on-start: true
#spring.security.user.name: root
#spring.security.user.password: root
#management.endpoints.web.exposure.include: *
properties.folder.path: ${user.home}/.arkcase/acm/acm-config-server-repo
branding.files.folder.path: ${user.home}/.arkcase/acm/acm-config-server-repo/branding
logging:
  file.max-history: 10
  file.max-size: 10MB
  file: logs/acmConfigServer.log
  level:
    com.armedia.acm.configserver: debug
    org.springframework.cloud.config: debug
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss,SSS} [%thread] %-5level %logger.%M - %msg%n"
jms.message.buffer.window: 1
acm.activemq:
  broker-url: ssl://localhost:61616
  keystore: ${user.home}/.arkcase/acm/private/arkcase.ks
  keystore-password: AcMd3v$
  truststore: ${user.home}/.arkcase/acm/private/arkcase.ts
  truststore-password: password
  user: "guest"
  password: "guest"
  default-destination: configuration.changed
  labels-destination: labels.changed
  ldap-destination: ldap.changed
  lookups-destination: lookups.changed
  rules-destination: rules.changed
  permissions-destination: permissions.changed
  timeout: 10 #seconds
arkcase.languages: "-de,-en,-en-in,-es,-fr,-hi,-ja,-pt,-ru,-zh-cn,-zh-tw"
